spring.application.name=yumi-blog
# Data Source
spring.datasource.url=jdbc:postgresql://localhost:5432/yumi_blog_developments
spring.datasource.username=yumi
spring.datasource.password=yumiblog
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

